// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { idusers } from "./Users";
import type { idimages } from "./Images";

/** Identifier type for companies */
export type idcompanies = string & { __flavor?: "id" };

/** Represents the table public.companies */
export default interface Companies {
  id: idcompanies;

  createdAt: Date;

  updatedAt: Date;

  deletedAt: Date | null;

  title: string;

  ownerId: idusers;

  address: string;

  phone: string;

  email: string;

  dateOfFounding: Date | null;

  cin: string | null;

  imageId: idimages | null;
}

/** Represents the initializer for the table public.companies */
export interface CompaniesInitializer {
  /** Default value: gen_random_uuid() */
  id?: idcompanies;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updatedAt?: Date;

  deletedAt?: Date | null;

  title: string;

  ownerId: idusers;

  address: string;

  phone: string;

  email: string;

  dateOfFounding?: Date | null;

  cin?: string | null;

  imageId?: idimages | null;
}

/** Represents the mutator for the table public.companies */
export interface CompaniesMutator {
  id?: idcompanies;

  createdAt?: Date;

  updatedAt?: Date;

  deletedAt?: Date | null;

  title?: string;

  ownerId?: idusers;

  address?: string;

  phone?: string;

  email?: string;

  dateOfFounding?: Date | null;

  cin?: string | null;

  imageId?: idimages | null;
}
