// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { idcompanies } from "./Companies";
import type { idusers } from "./Users";

/** Identifier type for companies_users */
export type idcompanies_users = string & { __flavor?: "id" };

/** Represents the table public.companies_users */
export default interface CompaniesUsers {
  id: idcompanies_users;

  createdAt: Date;

  updatedAt: Date;

  deletedAt: Date | null;

  companyId: idcompanies;

  userId: idusers;
}

/** Represents the initializer for the table public.companies_users */
export interface CompaniesUsersInitializer {
  /** Default value: gen_random_uuid() */
  id?: idcompanies_users;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updatedAt?: Date;

  deletedAt?: Date | null;

  companyId: idcompanies;

  userId: idusers;
}

/** Represents the mutator for the table public.companies_users */
export interface CompaniesUsersMutator {
  id?: idcompanies_users;

  createdAt?: Date;

  updatedAt?: Date;

  deletedAt?: Date | null;

  companyId?: idcompanies;

  userId?: idusers;
}
