// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { idusers } from "./Users";

/** Identifier type for images */
export type idimages = string & { __flavor?: "id" };

/** Represents the table public.images */
export default interface Images {
  id: idimages;

  title: string;

  createdAt: Date;

  updatedAt: Date;

  deletedAt: Date | null;

  ownerId: idusers;
}

/** Represents the initializer for the table public.images */
export interface ImagesInitializer {
  /** Default value: gen_random_uuid() */
  id?: idimages;

  title: string;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updatedAt?: Date;

  deletedAt?: Date | null;

  ownerId: idusers;
}

/** Represents the mutator for the table public.images */
export interface ImagesMutator {
  id?: idimages;

  title?: string;

  createdAt?: Date;

  updatedAt?: Date;

  deletedAt?: Date | null;

  ownerId?: idusers;
}
