// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Identifier type for public.locations */
export type LocationsId = string & { __brand: "LocationsId" };

/** Represents the table public.locations */
export default interface Locations {
  id: LocationsId;

  title: string;

  createdAt: Date;

  updatedAt: Date;

  deletedAt: Date | null;

  latitude: string | null;

  longitude: string | null;
}

/** Represents the initializer for the table public.locations */
export interface LocationsInitializer {
  /** Default value: gen_random_uuid() */
  id?: LocationsId;

  title: string;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updatedAt?: Date;

  deletedAt?: Date | null;

  latitude?: string | null;

  longitude?: string | null;
}

/** Represents the mutator for the table public.locations */
export interface LocationsMutator {
  id?: LocationsId;

  title?: string;

  createdAt?: Date;

  updatedAt?: Date;

  deletedAt?: Date | null;

  latitude?: string | null;

  longitude?: string | null;
}

export const locationsId = z.string() as unknown as z.Schema<LocationsId>;

export const locations = z.object({
  id: locationsId,
  title: z.string(),
  createdAt: z.date(),
  updatedAt: z.date(),
  deletedAt: z.date().nullable(),
  latitude: z.string().nullable(),
  longitude: z.string().nullable(),
}) as unknown as z.Schema<Locations>;

export const locationsInitializer = z.object({
  id: locationsId.optional(),
  title: z.string(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
  deletedAt: z.date().optional().nullable(),
  latitude: z.string().optional().nullable(),
  longitude: z.string().optional().nullable(),
}) as unknown as z.Schema<LocationsInitializer>;

export const locationsMutator = z.object({
  id: locationsId.optional(),
  title: z.string().optional(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
  deletedAt: z.date().optional().nullable(),
  latitude: z.string().optional().nullable(),
  longitude: z.string().optional().nullable(),
}) as unknown as z.Schema<LocationsMutator>;
