// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { imagesId, type ImagesId } from "./Images";
import { z } from "zod";

/** Identifier type for public.products */
export type ProductsId = string & { __brand: "ProductsId" };

/** Represents the table public.products */
export default interface Products {
  id: ProductsId;

  createdAt: Date | null;

  updatedAt: Date | null;

  deletedAt: Date | null;

  title: string;

  description: string | null;

  weight: string | null;

  volume: string | null;

  barcode: string | null;

  imageId: ImagesId | null;
}

/** Represents the initializer for the table public.products */
export interface ProductsInitializer {
  /** Default value: gen_random_uuid() */
  id?: ProductsId;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updatedAt?: Date | null;

  deletedAt?: Date | null;

  title: string;

  description?: string | null;

  weight?: string | null;

  volume?: string | null;

  barcode?: string | null;

  imageId?: ImagesId | null;
}

/** Represents the mutator for the table public.products */
export interface ProductsMutator {
  id?: ProductsId;

  createdAt?: Date | null;

  updatedAt?: Date | null;

  deletedAt?: Date | null;

  title?: string;

  description?: string | null;

  weight?: string | null;

  volume?: string | null;

  barcode?: string | null;

  imageId?: ImagesId | null;
}

export const productsId = z.string() as unknown as z.Schema<ProductsId>;

export const products = z.object({
  id: productsId,
  createdAt: z.date().nullable(),
  updatedAt: z.date().nullable(),
  deletedAt: z.date().nullable(),
  title: z.string(),
  description: z.string().nullable(),
  weight: z.string().nullable(),
  volume: z.string().nullable(),
  barcode: z.string().nullable(),
  imageId: imagesId.nullable(),
}) as unknown as z.Schema<Products>;

export const productsInitializer = z.object({
  id: productsId.optional(),
  createdAt: z.date().optional().nullable(),
  updatedAt: z.date().optional().nullable(),
  deletedAt: z.date().optional().nullable(),
  title: z.string(),
  description: z.string().optional().nullable(),
  weight: z.string().optional().nullable(),
  volume: z.string().optional().nullable(),
  barcode: z.string().optional().nullable(),
  imageId: imagesId.optional().nullable(),
}) as unknown as z.Schema<ProductsInitializer>;

export const productsMutator = z.object({
  id: productsId.optional(),
  createdAt: z.date().optional().nullable(),
  updatedAt: z.date().optional().nullable(),
  deletedAt: z.date().optional().nullable(),
  title: z.string().optional(),
  description: z.string().optional().nullable(),
  weight: z.string().optional().nullable(),
  volume: z.string().optional().nullable(),
  barcode: z.string().optional().nullable(),
  imageId: imagesId.optional().nullable(),
}) as unknown as z.Schema<ProductsMutator>;
