// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { idimages } from "./Images";

/** Identifier type for users */
export type idusers = string & { __flavor?: "id" };

/** Represents the table public.users */
export default interface Users {
  id: idusers;

  createdAt: Date;

  updatedAt: Date;

  deletedAt: Date | null;

  firstName: string;

  lastName: string;

  username: string;

  email: string | null;

  phone: string | null;

  dateOfBirth: Date | null;

  dateOfEmployment: Date | null;

  dateOfTermination: Date | null;

  imageId: idimages | null;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  /** Default value: gen_random_uuid() */
  id?: idusers;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updatedAt?: Date;

  deletedAt?: Date | null;

  firstName: string;

  lastName: string;

  username: string;

  email?: string | null;

  phone?: string | null;

  dateOfBirth?: Date | null;

  dateOfEmployment?: Date | null;

  dateOfTermination?: Date | null;

  imageId?: idimages | null;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  id?: idusers;

  createdAt?: Date;

  updatedAt?: Date;

  deletedAt?: Date | null;

  firstName?: string;

  lastName?: string;

  username?: string;

  email?: string | null;

  phone?: string | null;

  dateOfBirth?: Date | null;

  dateOfEmployment?: Date | null;

  dateOfTermination?: Date | null;

  imageId?: idimages | null;
}
