"$schema"= "http://json.schemastore.org/prettierrc"
arrowParens= "always"
bracketSpacing= true
bracketSameLine= true
printWidth= 128
proseWrap= "preserve"
tabWidth= 2
trailingComma= "es5"
jsxSingleQuote= false
semi= true
endOfLine= "auto"
singleQuote= false
plugins= ["prettier-plugin-tailwindcss"]
tailwindFunctions= ["tv"]
