export const Icons = {
  add: "ph:plus" as const,
  "add-item": "mdi:basket-plus-outline" as const,
  "arrow-down": "ph:caret-down" as const,
  "arrow-right": "ph:caret-right" as const,
  "arrow-up": "ph:caret-up" as const,
  barcode: "ph:barcode" as const,
  "barcode-remove": "iconoir:scan-barcode" as const,
  booking: "hugeicons:restaurant-01" as const,
  beer: "ph:beer-bottle-light" as const,
  chicken: "healthicons:animal-chicken-outline" as const,
  close: "ph:x" as const,
  employee: "mdi:user-badge-outline" as const,
  folder: "ph:folder" as const,
  input: "streamline:input-box" as const,
  inventory: "system-uicons:boxes" as const,
  loading: "ph:circle-notch" as const,
  manage: "fluent:clipboard-text-edit-24-regular" as const,
  menu: "ph:dots-three-circle-thin" as const,
  "remove-item": "mdi:basket-minus-outline" as const,
  settings: "ph:gear" as const,
  supplier: "ph:truck" as const,
};
